AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ServerlessApi:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.13
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.13
      CodeUri: .
      Timeout: 30
      Environment:
        Variables:
          ENV: local
          DYNAMODB_ENDPOINT: http://localhost:8000
          OPENAI_API_KEY: placeholder-value
          STRIPE_API_KEY: placeholder-value
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            Cors:
              AllowMethods: "'GET,POST,OPTIONS'"
              AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              AllowOrigin: "'*'"