name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build wheel

          # Create and activate virtual environment
          python -m venv venv
          source venv/bin/activate

          # Create package directory
          mkdir -p package

          # Install pydantic and its dependencies first with special handling
          pip install \
            --platform manylinux2014_x86_64 \
            --implementation cp \
            --python-version 3.9 \
            --only-binary=:all: \
            --target package \
            pydantic==2.10.5 \
            pydantic-core==2.27.2

          # Install the rest of the dependencies
          pip install \
            --platform manylinux2014_x86_64 \
            --implementation cp \
            --python-version 3.9 \
            --only-binary=:all: \
            --target package \
            -r requirements.txt

      - name: Clean up unnecessary files
        run: |
          cd package
          find . -type d -name "__pycache__" -exec rm -rf {} +
          find . -type d -name "*.dist-info" -exec rm -rf {} +
          find . -type d -name "*.egg-info" -exec rm -rf {} +
          find . -type f -name "*.pyc" -delete

      - name: Prepare deployment package
        run: |
          cp lambda_function.py package/
          cp -r src/ package/ || true
          cd package
          zip -r ../deployment-package.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:717279698773:function:serverless-api-lambda \
            --zip-file fileb://deployment-package.zip